
import type { Project, ProjectType } from '@/components/projects/types';

export const PROJECT_TYPES: ProjectType[] = ["All", "Web", "Mobile", "Systems"];

export const MOCK_PROJECTS: Project[] = [
  {
    id: '1',
    title: 'OpenSource Hub',
    description: 'A platform for discovering, collaborating on, and managing open-source projects.',
    longDescription: "OpenSource Hub aims to be a central nexus for the open-source community. It facilitates project discovery through advanced search and categorization, supports collaboration with integrated version control and issue tracking, and provides tools for project maintainers to manage contributions and releases effectively. Built for transparency and community growth.",
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'community platform',
    techStack: ['Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'Docker', 'GraphQL'],
    liveUrl: '#',
    repoUrl: 'https://github.com/Symoh242',
    projectType: 'Web',
  },
  {
    id: '2',
    title: 'Mobile Fitness App "FitTrack"',
    description: 'Cross-platform app for workout tracking, meal planning, and progress monitoring.',
    longDescription: 'FitTrack is a comprehensive mobile fitness companion available on iOS and Android. It offers personalized workout plans, a vast exercise library with video demonstrations, calorie and macronutrient tracking, integration with wearables (Apple Health, Google Fit), and community features for motivation.',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'fitness app',
    techStack: ['React Native', 'TypeScript', 'Firebase', 'GraphQL', 'Node.js'],
    liveUrl: '#',
    projectType: 'Mobile',
  },
  {
    id: '3',
    title: 'Royaltech Limited',
    description: "Delivering cutting-edge data analytics and enterprise solutions for Royaltech Limited's clients.",
    longDescription: "Royaltech Limited leverages advanced technologies to provide clients with powerful data analytics dashboards, business intelligence tools, and custom enterprise software. Their solutions, like the flagship InsightEngine, empower organizations to make data-driven decisions, optimize operations, and achieve strategic goals. Focus on scalability, security, and real-time insights.",
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'tech solutions',
    techStack: ['Python (Flask)', 'React', 'D3.js', 'Kafka', 'Spark', 'MongoDB'],
    liveUrl: 'https://royaltech-system-1-version.vercel.app/',
    repoUrl: '#',
    projectType: 'Systems',
  },
  {
    id: '4',
    title: 'Simon Styles Ltd.',
    description: "Professional portfolio and service showcase for Simon Styles Ltd., detailing expertise and projects.",
    longDescription: "The official online presence of Simon Styles Ltd., showcasing a range of successfully delivered web, mobile, and system development projects. This platform highlights the skills, methodologies, and innovative solutions offered, providing a comprehensive overview of capabilities and an easy way for potential clients to connect.",
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'portfolio website',
    techStack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Genkit', 'Gemini AI'],
    liveUrl: 'https://simon-styles-openhub.vercel.app/',
    repoUrl: 'https://github.com/Symoh242',
    projectType: 'Web',
  },
  {
    id: '5',
    title: 'SaaS Booking System "AppointEase"',
    description: 'Cloud-based appointment scheduling software for service-based businesses.',
    longDescription: 'AppointEase simplifies appointment management for businesses like salons, clinics, and consultants. Features include online booking, automated reminders (SMS/email), staff management, service customization, payment integration, and reporting tools. It is a multi-tenant SaaS application.',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'booking interface',
    techStack: ['Ruby on Rails', 'React', 'PostgreSQL', 'Sidekiq', 'Stripe API'],
    liveUrl: '#',
    repoUrl: '#',
    projectType: 'Web',
  },
  {
    id: '6',
    title: 'COMPCODES LIMITED',
    description: 'Bespoke software development and system integration by COMPCODES LIMITED.',
    longDescription: "COMPCODES LIMITED specializes in crafting tailored software solutions for diverse business needs. Their services include web and mobile application development, custom CRM systems like their successful ClientConnect platform, and complex system integrations. They are committed to delivering high-quality, scalable, and maintainable code.",
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'software company',
    techStack: ['Django (Python)', 'Vue.js', 'PostgreSQL', 'Celery', 'REST APIs'],
    liveUrl: '#',
    repoUrl: 'https://github.com/Symoh242',
    projectType: 'Systems',
  },
];
