
import type { Project, ProjectType } from '@/components/projects/types';

export const PROJECT_TYPES: ProjectType[] = ["All", "Web", "Mobile", "Systems"];

export const MOCK_PROJECTS: Project[] = [
  {
    id: '1',
    title: 'E-commerce Platform "ShopSphere"',
    description: 'A full-featured online marketplace with secure payments and vendor dashboards.',
    longDescription: 'ShopSphere is a robust e-commerce platform designed to connect buyers and sellers. Key features include multi-vendor support, integrated payment gateways (Stripe, PayPal), advanced product search and filtering, order management, and user review systems. Built with a microservices architecture for scalability.',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'online store',
    techStack: ['Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'Docker', 'AWS'],
    liveUrl: 'https://bms-28in.vercel.app/',
    repoUrl: '#',
    projectType: 'Web',
  },
  {
    id: '2',
    title: 'Mobile Fitness App "FitTrack"',
    description: 'Cross-platform app for workout tracking, meal planning, and progress monitoring.',
    longDescription: 'FitTrack is a comprehensive mobile fitness companion available on iOS and Android. It offers personalized workout plans, a vast exercise library with video demonstrations, calorie and macronutrient tracking, integration with wearables (Apple Health, Google Fit), and community features for motivation.',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'fitness app',
    techStack: ['React Native', 'TypeScript', 'Firebase', 'GraphQL', 'Node.js'],
    liveUrl: '#',
    projectType: 'Mobile',
  },
  {
    id: '3',
    title: 'Data Analytics Dashboard "InsightEngine"',
    description: 'A real-time data visualization and business intelligence tool for enterprise clients.',
    longDescription: 'InsightEngine provides businesses with actionable insights through an intuitive dashboard. It supports various data sources, offers customizable widgets, real-time data streaming, predictive analytics modules, and automated reporting. Security and data privacy are paramount, with role-based access control and encryption.',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'data dashboard',
    techStack: ['Python (Flask)', 'React', 'D3.js', 'Kafka', 'Spark', 'MongoDB'],
    liveUrl: 'https://royaltech-system-1-version.vercel.app/',
    repoUrl: '#',
    projectType: 'Systems',
  },
  {
    id: '4',
    title: 'Personal Portfolio Website "Simon Styles Portfolio"',
    description: 'A modern, responsive portfolio showcasing Simon\'s skills and projects.',
    longDescription: 'This very portfolio website, designed to be clean, fast, and accessible. It highlights key projects, skills, and provides an easy way to get in touch. It features an AI-powered showcase generator and dynamic project filtering. ',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'portfolio website',
    techStack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Genkit', 'Gemini AI'],
    liveUrl: 'https://simon-styles-openhub.vercel.app/',
    projectType: 'Web',
  },
  {
    id: '5',
    title: 'SaaS Booking System "AppointEase"',
    description: 'Cloud-based appointment scheduling software for service-based businesses.',
    longDescription: 'AppointEase simplifies appointment management for businesses like salons, clinics, and consultants. Features include online booking, automated reminders (SMS/email), staff management, service customization, payment integration, and reporting tools. It is a multi-tenant SaaS application.',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'booking interface',
    techStack: ['Ruby on Rails', 'React', 'PostgreSQL', 'Sidekiq', 'Stripe API'],
    liveUrl: '#',
    repoUrl: '#',
    projectType: 'Web',
  },
  {
    id: '6',
    title: 'Internal CRM Tool "ClientConnect"',
    description: 'A custom CRM solution for managing client interactions and sales pipelines.',
    longDescription: 'ClientConnect is an internal tool developed to streamline client relationship management. It features contact management, deal tracking, task automation, communication logging, and sales forecasting. Designed for ease of use and integration with existing company systems.',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'crm dashboard',
    techStack: ['Django (Python)', 'Vue.js', 'PostgreSQL', 'Celery', 'REST APIs'],
    repoUrl: '#',
    projectType: 'Systems',
  },
];
