
export interface LaptopSpec {
  key: string;
  value: string;
}

export type LaptopBadgeVariant = 'default' | 'secondary' | 'destructive' | 'outline' | 'hotdeal' | 'new';

export interface Laptop {
  id: string;
  name: string;
  brand: string;
  price: number;
  originalPrice?: number; // For strikethrough pricing
  imageUrl: string;
  dataAiHint?: string;
  shortDescription: string; // This will be used as the main spec line below title
  specs: LaptopSpec[]; // Detailed specs, maybe for a detail page later
  stock: number;
  badgeText?: string; // e.g., "BRAND NEW", "SOLD OUT", "SALE"
  badgeVariant?: LaptopBadgeVariant;
  promotionalText?: string; // e.g., "Free Wireless Mouse"
  // Fields for potential filtering (can be expanded)
  processorType?: string;
  screenSize?: string;
  storageType?: string;
  graphicsType?: string;
  operatingSystem?: string;
}

export const MOCK_LAPTOPS: Laptop[] = [
  {
    id: 'laptop-1',
    name: 'ASUS X543M, Celeron N4020, 4 GB Ram, 1 TB',
    brand: 'Asus',
    price: 26499,
    originalPrice: 28000,
    imageUrl: 'https://smartbuy.co.ke/wp-content/uploads/2021/04/ASUS-X543M-1.jpg',
    dataAiHint: 'asus laptop',
    shortDescription: 'N4020, 4 GB Ram, 1 TB',
    specs: [
      { key: 'Processor', value: 'Intel Celeron N4020' },
      { key: 'RAM', value: '4GB DDR4' },
      { key: 'Storage', value: '1TB HDD' },
      { key: 'Display', value: '15.6" HD' },
    ],
    stock: 15,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    promotionalText: '+ Free Mouse',
    processorType: 'Celeron N4020',
    screenSize: '15.6"',
    storageType: '1TB HDD',
    graphicsType: 'Integrated',
    operatingSystem: 'Windows 10'
  },
  {
    id: 'laptop-2',
    name: 'Lenovo IdeaPad S145-15 Celeron, 4 GB Ram, 1 TB',
    brand: 'Lenovo',
    price: 27999,
    originalPrice: 31000,
    imageUrl: 'https://smartbuy.co.ke/wp-content/uploads/2021/06/Lenovo-S145.jpg',
    dataAiHint: 'lenovo s145',
    shortDescription: 'Celeron, 4 GB Ram, 1 TB',
    specs: [
      { key: 'Processor', value: 'Intel Celeron' },
      { key: 'RAM', value: '4GB DDR4' },
      { key: 'Storage', value: '1TB HDD' },
      { key: 'Display', value: '15.6" HD' },
    ],
    stock: 10,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    promotionalText: 'Free Wireless Mouse',
    processorType: 'Celeron',
    screenSize: '15.6"',
    storageType: '1TB HDD',
    graphicsType: 'Integrated',
    operatingSystem: 'Windows 10'
  },
  {
    id: 'laptop-3',
    name: 'Lenovo IdeaPad 3-14 Celeron, 4GB Ram, 1TB',
    brand: 'Lenovo',
    price: 29999,
    originalPrice: 33000,
    imageUrl: 'https://smartbuy.co.ke/wp-content/uploads/2021/07/Lenovo-IdeaPad-3-14-celeron-3-300x300.jpg',
    dataAiHint: 'lenovo ideapad',
    shortDescription: 'Celeron, 4GB Ram, 1TB',
    specs: [
      { key: 'Processor', value: 'Intel Celeron' },
      { key: 'RAM', value: '4GB DDR4' },
      { key: 'Storage', value: '1TB HDD' },
      { key: 'Display', value: '14" HD' },
    ],
    stock: 10,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    promotionalText: '1 Year Warranty',
    processorType: 'Celeron',
    screenSize: '14"',
    storageType: '1TB HDD',
    graphicsType: 'Integrated',
    operatingSystem: 'Windows 11'
  },
  {
    id: 'laptop-4',
    name: 'Lenovo IdeaPad 330, Intel Celeron, 1TB, 4GB',
    brand: 'Lenovo',
    price: 29999,
    originalPrice: 32000,
    imageUrl: 'https://smartbuy.co.ke/wp-content/uploads/2021/09/LENOVO-IDEAPAD-330.jpg',
    dataAiHint: 'lenovo ideapad',
    shortDescription: 'Intel Celeron, 1TB, 4GB',
    specs: [
      { key: 'Processor', value: 'Intel Celeron' },
      { key: 'RAM', value: '4GB DDR4' },
      { key: 'Storage', value: '1TB HDD' },
      { key: 'Display', value: '15.6" HD' },
    ],
    stock: 7,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    processorType: 'Celeron',
    screenSize: '15.6"',
    storageType: '1TB HDD',
    graphicsType: 'Integrated',
    operatingSystem: 'DOS'
  },
  {
    id: 'laptop-5',
    name: 'HP 250 G8 Celeron N4020, 4GB Ram, 500GB',
    brand: 'HP',
    price: 29999,
    originalPrice: 33000,
    imageUrl: 'https://smartbuy.co.ke/wp-content/uploads/2022/01/HP-250-G8-CELERON-4.jpg',
    dataAiHint: 'hp laptop',
    shortDescription: 'N4020, 4GB Ram, 500GB',
    specs: [
      { key: 'Processor', value: 'Intel Celeron N4020' },
      { key: 'RAM', value: '4GB DDR4' },
      { key: 'Storage', value: '500GB HDD' },
      { key: 'Display', value: '15.6" HD' },
    ],
    stock: 12,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    processorType: 'Celeron N4020',
    screenSize: '15.6"',
    storageType: '500GB HDD',
    graphicsType: 'Integrated',
    operatingSystem: 'Windows 10'
  },
  {
    id: 'laptop-6',
    name: 'HP 250 G7 Celeron N4020, 4GB Ram, 500GB',
    brand: 'HP',
    price: 29999,
    originalPrice: 31000,
    imageUrl: 'https://smartbuy.co.ke/wp-content/uploads/2022/03/hp-250-g7-celeron-.jpg',
    dataAiHint: 'hp g7 laptop',
    shortDescription: 'N4020, 4GB Ram, 500GB',
    specs: [
      { key: 'Processor', value: 'Intel Celeron N4020' },
      { key: 'RAM', value: '4GB DDR4' },
      { key: 'Storage', 'value': '500GB HDD' },
      { key: 'Display', value: '15.6" HD' },
    ],
    stock: 9,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    promotionalText: '+ Free Bag',
    processorType: 'Celeron N4020',
    screenSize: '15.6"',
    storageType: '500GB HDD',
    graphicsType: 'Integrated',
    operatingSystem: 'Windows 10'
  },
  {
    id: 'laptop-7',
    name: 'Lenovo IdeaPad 3 15 IGL05, Intel Celeron',
    brand: 'Lenovo',
    price: 29999,
    originalPrice: 31000,
    imageUrl: 'https://smartbuy.co.ke/wp-content/uploads/2022/02/Lenovo-V15-G2-1.jpg',
    dataAiHint: 'lenovo ideapad',
    shortDescription: 'Intel Celeron, 4GB, 1TB',
     specs: [
      { key: 'Processor', value: 'Intel Celeron' },
      { key: 'RAM', value: '4GB DDR4' },
      { key: 'Storage', value: '1TB HDD' },
      { key: 'Display', value: '15.6" HD' },
    ],
    stock: 11,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    processorType: 'Celeron',
    screenSize: '15.6"',
    storageType: '1TB HDD',
    graphicsType: 'Integrated',
    operatingSystem: 'Windows 11'
  },
  {
    id: 'laptop-8',
    name: 'HP 14 Notebook, Celeron, 4 GB Ram, 500 GB HDD',
    brand: 'HP',
    price: 33999,
    originalPrice: 36000,
    imageUrl: 'https://nairobicomputershop.co.ke/media/products/2021/04/HP-Notebook-14-Intel-Celeron-4GB-RAM-500GB-Hard-Drive-3.jpg',
    dataAiHint: 'hp notebook',
    shortDescription: 'Celeron, 4 GB Ram, 500 GB HDD',
    specs: [
      { key: 'Processor', value: 'Intel Celeron' },
      { key: 'RAM', value: '4GB DDR4' },
      { key: 'Storage', value: '500GB HDD' },
      { key: 'Display', value: '14" HD' },
    ],
    stock: 5,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    processorType: 'Celeron',
    screenSize: '14"',
    storageType: '500GB HDD',
    graphicsType: 'Integrated',
    operatingSystem: 'Windows 10'
  },
  {
    id: 'laptop-9',
    name: 'Dell Inspiron 15 3000, Core i3, 8GB RAM, 256GB SSD',
    brand: 'Dell',
    price: 45999,
    imageUrl: 'https://hewlettcomputersolution.co.ke/wp-content/uploads/2023/12/Dell-Inspiron-15-3000-I3-10th-Gen-8-128-Touch-Laptop.png',
    dataAiHint: 'dell inspiron laptop',
    shortDescription: 'Core i3, 8GB RAM, 256GB SSD',
    specs: [
      { key: 'Processor', value: 'Intel Core i3-1115G4' },
      { key: 'RAM', value: '8GB DDR4' },
      { key: 'Storage', value: '256GB SSD' },
      { key: 'Display', value: '15.6" FHD' },
    ],
    stock: 20,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    processorType: 'Core i3',
    screenSize: '15.6"',
    storageType: '256GB SSD',
    graphicsType: 'Integrated Intel UHD',
    operatingSystem: 'Windows 11'
  },
  {
    id: 'laptop-10',
    name: 'Apple MacBook Air M1, 8GB RAM, 256GB SSD',
    brand: 'Apple',
    price: 109999,
    originalPrice: 115000,
    imageUrl: 'https://nairobicomputershop.co.ke/media/products/2022/07/MC_1.jpg',
    dataAiHint: 'macbook air silver',
    shortDescription: 'M1 Chip, 8GB RAM, 256GB SSD',
    specs: [
      { key: 'Processor', value: 'Apple M1 Chip' },
      { key: 'RAM', value: '8GB Unified Memory' },
      { key: 'Storage', value: '256GB SSD' },
      { key: 'Display', value: '13.3" Retina' },
    ],
    stock: 10,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    processorType: 'Apple M1',
    screenSize: '13.3"',
    storageType: '256GB SSD',
    graphicsType: 'Integrated 7-core GPU',
    operatingSystem: 'macOS'
  },
  {
    id: 'laptop-11',
    name: 'HP Pavilion 15, Ryzen 5, 8GB RAM, 512GB SSD',
    brand: 'HP',
    price: 68500,
    imageUrl: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed',
    dataAiHint: 'hp pavilion blue',
    shortDescription: 'Ryzen 5, 8GB RAM, 512GB SSD',
    specs: [
      { key: 'Processor', value: 'AMD Ryzen 5 5500U' },
      { key: 'RAM', value: '8GB DDR4' },
      { key: 'Storage', value: '512GB NVMe SSD' },
      { key: 'Display', value: '15.6" FHD IPS' },
    ],
    stock: 18,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    promotionalText: 'Includes Backpack',
    processorType: 'Ryzen 5',
    screenSize: '15.6"',
    storageType: '512GB SSD',
    graphicsType: 'AMD Radeon Graphics',
    operatingSystem: 'Windows 11'
  },
  {
    id: 'laptop-12',
    name: 'Asus VivoBook 14, Core i5, 12GB RAM, 512GB SSD',
    brand: 'Asus',
    price: 72000,
    originalPrice: 75000,
    imageUrl: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9',
    dataAiHint: 'asus vivobook grey',
    shortDescription: 'Core i5, 12GB RAM, 512GB SSD',
    specs: [
      { key: 'Processor', value: 'Intel Core i5-1135G7' },
      { key: 'RAM', value: '12GB DDR4' },
      { key: 'Storage', value: '512GB SSD' },
      { key: 'Display', value: '14" FHD NanoEdge' },
    ],
    stock: 8,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    processorType: 'Core i5',
    screenSize: '14"',
    storageType: '512GB SSD',
    graphicsType: 'Intel Iris Xe',
    operatingSystem: 'Windows 10'
  },
  {
    id: 'laptop-13',
    name: 'Lenovo Legion 5, Ryzen 7, 16GB RAM, 1TB SSD, RTX 3060',
    brand: 'Lenovo',
    price: 145000,
    imageUrl: 'https://images.unsplash.com/photo-1618225042443-a614b19b6343',
    dataAiHint: 'lenovo legion gaming',
    shortDescription: 'Ryzen 7, RTX 3060, 16GB RAM',
    specs: [
      { key: 'Processor', value: 'AMD Ryzen 7 5800H' },
      { key: 'RAM', value: '16GB DDR4' },
      { key: 'Storage', value: '1TB NVMe SSD' },
      { key: 'Display', value: '15.6" FHD 165Hz' },
      { key: 'Graphics', value: 'NVIDIA GeForce RTX 3060 6GB' },
    ],
    stock: 5,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    promotionalText: 'RGB Keyboard',
    processorType: 'Ryzen 7',
    screenSize: '15.6"',
    storageType: '1TB SSD',
    graphicsType: 'NVIDIA RTX 3060',
    operatingSystem: 'Windows 11'
  },
  {
    id: 'laptop-14',
    name: 'Dell XPS 13, Core i7, 16GB RAM, 512GB SSD',
    brand: 'Dell',
    price: 159999,
    imageUrl: 'https://images.unsplash.com/photo-1542393545-10f5cde2c810',
    dataAiHint: 'dell xps silver',
    shortDescription: 'Core i7, 16GB RAM, 512GB SSD, UHD+',
    specs: [
      { key: 'Processor', value: 'Intel Core i7-1260P' },
      { key: 'RAM', value: '16GB LPDDR5' },
      { key: 'Storage', value: '512GB NVMe SSD' },
      { key: 'Display', value: '13.4" FHD+ InfinityEdge' },
    ],
    stock: 7,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    processorType: 'Core i7',
    screenSize: '13.4"',
    storageType: '512GB SSD',
    graphicsType: 'Intel Iris Xe',
    operatingSystem: 'Windows 11 Pro'
  },
  {
    id: 'laptop-15',
    name: 'Apple MacBook Pro 14 M2 Pro, 16GB RAM, 512GB SSD',
    brand: 'Apple',
    price: 249999,
    imageUrl: 'https://images.unsplash.com/photo-1569770218135-bea267ed7e84',
    dataAiHint: 'macbook pro spacegrey',
    shortDescription: 'M2 Pro, 16GB RAM, 512GB SSD',
    specs: [
      { key: 'Processor', value: 'Apple M2 Pro Chip (10-core CPU, 16-core GPU)' },
      { key: 'RAM', value: '16GB Unified Memory' },
      { key: 'Storage', value: '512GB SSD' },
      { key: 'Display', value: '14.2" Liquid Retina XDR' },
    ],
    stock: 6,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    promotionalText: 'Pro Power',
    processorType: 'Apple M2 Pro',
    screenSize: '14.2"',
    storageType: '512GB SSD',
    graphicsType: 'Integrated 16-core GPU',
    operatingSystem: 'macOS'
  },
  {
    id: 'laptop-16',
    name: 'Asus ROG Zephyrus G14, Ryzen 9, 16GB RAM, 1TB SSD, RTX 3050Ti',
    brand: 'Asus',
    price: 165000,
    originalPrice: 175000,
    imageUrl: 'https://images.unsplash.com/photo-1643448981657-3a443919b35b',
    dataAiHint: 'asus rog white',
    shortDescription: 'Ryzen 9, RTX 3050Ti, AniMe Matrix',
    specs: [
      { key: 'Processor', value: 'AMD Ryzen 9 6900HS' },
      { key: 'RAM', value: '16GB DDR5' },
      { key: 'Storage', value: '1TB PCIe 4.0 SSD' },
      { key: 'Display', value: '14" QHD+ 120Hz Pantone Validated' },
      { key: 'Graphics', value: 'NVIDIA GeForce RTX 3050 Ti 4GB' },
    ],
    stock: 9,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    promotionalText: 'AniMe Matrix Display',
    processorType: 'Ryzen 9',
    screenSize: '14"',
    storageType: '1TB SSD',
    graphicsType: 'NVIDIA RTX 3050Ti',
    operatingSystem: 'Windows 11'
  },
  {
    id: 'laptop-17',
    name: 'HP Envy x360 13, Core i5, 8GB RAM, 512GB SSD',
    brand: 'HP',
    price: 98000,
    imageUrl: 'https://images.unsplash.com/photo-1616443185387-4a41334b0d50',
    dataAiHint: 'hp envy convertible',
    shortDescription: 'Convertible, Core i5, 8GB RAM, 512GB SSD',
    specs: [
      { key: 'Processor', value: 'Intel Core i5-1230U' },
      { key: 'RAM', value: '8GB DDR4' },
      { key: 'Storage', value: '512GB NVMe SSD' },
      { key: 'Display', value: '13.3" FHD Touchscreen OLED' },
    ],
    stock: 11,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    processorType: 'Core i5',
    screenSize: '13.3"',
    storageType: '512GB SSD',
    graphicsType: 'Intel Iris Xe',
    operatingSystem: 'Windows 11'
  },
  {
    id: 'laptop-18',
    name: 'Lenovo ThinkPad E14 Gen 3, Ryzen 5, 16GB RAM, 512GB SSD',
    brand: 'Lenovo',
    price: 85000,
    imageUrl: 'https://plus.unsplash.com/premium_photo-1679397828082-93856237c569',
    dataAiHint: 'lenovo thinkpad black',
    shortDescription: 'Ryzen 5, 16GB RAM, Business Laptop',
    specs: [
      { key: 'Processor', value: 'AMD Ryzen 5 5600U' },
      { key: 'RAM', value: '16GB DDR4' },
      { key: 'Storage', value: '512GB NVMe SSD' },
      { key: 'Display', value: '14" FHD Anti-glare' },
    ],
    stock: 14,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    promotionalText: 'ThinkShield Security',
    processorType: 'Ryzen 5',
    screenSize: '14"',
    storageType: '512GB SSD',
    graphicsType: 'AMD Radeon Graphics',
    operatingSystem: 'Windows 10 Pro'
  },
  {
    id: 'laptop-19',
    name: 'Dell Latitude 7420, Core i5, 16GB RAM, 256GB SSD',
    brand: 'Dell',
    price: 115000,
    originalPrice: 125000,
    imageUrl: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2',
    dataAiHint: 'dell latitude business',
    shortDescription: 'Business, Core i5, 16GB RAM, Lightweight',
    specs: [
      { key: 'Processor', value: 'Intel Core i5-1145G7 vPro' },
      { key: 'RAM', value: '16GB DDR4' },
      { key: 'Storage', value: '256GB NVMe SSD' },
      { key: 'Display', value: '14" FHD Anti-glare' },
    ],
    stock: 10,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    processorType: 'Core i5',
    screenSize: '14"',
    storageType: '256GB SSD',
    graphicsType: 'Intel Iris Xe',
    operatingSystem: 'Windows 10 Pro'
  },
  {
    id: 'laptop-20',
    name: 'Asus ZenBook Duo 14, Core i7, 16GB RAM, 1TB SSD, ScreenPad Plus',
    brand: 'Asus',
    price: 199999,
    imageUrl: 'https://images.unsplash.com/photo-1606220863836-c69224b75245',
    dataAiHint: 'asus zenbook duo',
    shortDescription: 'Dual Screen, Core i7, 16GB RAM, 1TB SSD',
    specs: [
      { key: 'Processor', value: 'Intel Core i7-12700H' },
      { key: 'RAM', value: '16GB LPDDR5' },
      { key: 'Storage', value: '1TB PCIe 4.0 SSD' },
      { key: 'Display', value: '14.5" 2.8K OLED Touch + 12.7" ScreenPad Plus' },
      { key: 'Graphics', value: 'Intel Iris Xe' },
    ],
    stock: 4,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    promotionalText: 'Stylus Included',
    processorType: 'Core i7',
    screenSize: '14.5"',
    storageType: '1TB SSD',
    graphicsType: 'Intel Iris Xe',
    operatingSystem: 'Windows 11 Pro'
  },
  {
    id: 'laptop-21',
    name: 'HP Spectre x360 14, Core i7, 16GB RAM, 1TB SSD, OLED',
    brand: 'HP',
    price: 185000,
    imageUrl: 'https://images.unsplash.com/photo-1616443185387-4a41334b0d50',
    dataAiHint: 'hp spectre gold',
    shortDescription: 'Convertible, Core i7, OLED, 1TB SSD',
    specs: [
      { key: 'Processor', value: 'Intel Core i7-1355U' },
      { key: 'RAM', value: '16GB LPDDR4x' },
      { key: 'Storage', value: '1TB NVMe SSD' },
      { key: 'Display', value: '13.5" 3K2K OLED Touchscreen' },
    ],
    stock: 6,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    processorType: 'Core i7',
    screenSize: '13.5"',
    storageType: '1TB SSD',
    graphicsType: 'Intel Iris Xe',
    operatingSystem: 'Windows 11 Home'
  },
  {
    id: 'laptop-22',
    name: 'Lenovo Yoga Slim 7 Pro, Ryzen 7, 16GB RAM, 512GB SSD',
    brand: 'Lenovo',
    price: 110000,
    originalPrice: 120000,
    imageUrl: 'https://images.unsplash.com/photo-1602081036496-c1483b3815fe',
    dataAiHint: 'lenovo yoga slim',
    shortDescription: 'Ryzen 7, 16GB RAM, QHD Display',
    specs: [
      { key: 'Processor', value: 'AMD Ryzen 7 5800HS' },
      { key: 'RAM', value: '16GB DDR4' },
      { key: 'Storage', value: '512GB NVMe SSD' },
      { key: 'Display', value: '14" 2.8K QHD IPS 90Hz' },
    ],
    stock: 10,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    promotionalText: 'Lightweight Design',
    processorType: 'Ryzen 7',
    screenSize: '14"',
    storageType: '512GB SSD',
    graphicsType: 'AMD Radeon Graphics',
    operatingSystem: 'Windows 11'
  },
  {
    id: 'laptop-23',
    name: 'Microsoft Surface Laptop 5 13.5", Core i5, 8GB RAM, 256GB SSD',
    brand: 'Microsoft',
    price: 125000,
    imageUrl: 'https://images.unsplash.com/photo-1662010022067-5a4014c5b36e',
    dataAiHint: 'surface laptop platinum',
    shortDescription: 'Core i5, 8GB RAM, PixelSense Display',
    specs: [
      { key: 'Processor', value: 'Intel Core i5-1235U' },
      { key: 'RAM', value: '8GB LPDDR5x' },
      { key: 'Storage', value: '256GB SSD' },
      { key: 'Display', value: '13.5” PixelSense Touchscreen (2256 x 1504)' },
    ],
    stock: 9,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    processorType: 'Core i5',
    screenSize: '13.5"',
    storageType: '256GB SSD',
    graphicsType: 'Intel Iris Xe',
    operatingSystem: 'Windows 11'
  },
  {
    id: 'laptop-24',
    name: 'Acer Aspire 5, Core i5, 8GB RAM, 512GB SSD, MX450',
    brand: 'Acer',
    price: 65000,
    imageUrl: 'https://images.unsplash.com/photo-1589561084212-7235b0445d44',
    dataAiHint: 'acer aspire silver',
    shortDescription: 'Core i5, 8GB RAM, NVIDIA MX450',
    specs: [
      { key: 'Processor', value: 'Intel Core i5-1135G7' },
      { key: 'RAM', value: '8GB DDR4' },
      { key: 'Storage', value: '512GB NVMe SSD' },
      { key: 'Display', value: '15.6" FHD IPS' },
      { key: 'Graphics', value: 'NVIDIA GeForce MX450 2GB' },
    ],
    stock: 15,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    processorType: 'Core i5',
    screenSize: '15.6"',
    storageType: '512GB SSD',
    graphicsType: 'NVIDIA MX450',
    operatingSystem: 'Windows 10'
  },
  {
    id: 'laptop-25',
    name: 'Samsung Galaxy Book3 Pro 16", Core i7, 16GB RAM, 1TB SSD',
    brand: 'Samsung',
    price: 170000,
    imageUrl: 'https://images.unsplash.com/photo-1676813333332-9df75f1b2b3a',
    dataAiHint: 'samsung galaxybook',
    shortDescription: 'AMOLED 3K, Core i7, 16GB RAM, 1TB SSD',
    specs: [
      { key: 'Processor', value: 'Intel Core i7-1360P' },
      { key: 'RAM', value: '16GB LPDDR5' },
      { key: 'Storage', value: '1TB NVMe SSD' },
      { key: 'Display', value: '16" Dynamic AMOLED 2X (2880 x 1800) 120Hz' },
    ],
    stock: 7,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    promotionalText: 'Slim & Light',
    processorType: 'Core i7',
    screenSize: '16"',
    storageType: '1TB SSD',
    graphicsType: 'Intel Iris Xe',
    operatingSystem: 'Windows 11'
  },
];
