export interface LaptopSpec {
  key: string;
  value: string;
}

export type LaptopBadgeVariant = 'default' | 'secondary' | 'destructive' | 'outline' | 'hotdeal' | 'new';

export interface Laptop {
  id: string;
  name: string;
  brand: string;
  price: number;
  originalPrice?: number; // For strikethrough pricing
  imageUrl: string;
  dataAiHint?: string;
  shortDescription: string; // This will be used as the main spec line below title
  specs: LaptopSpec[]; // Detailed specs, maybe for a detail page later
  stock: number;
  badgeText?: string; // e.g., "BRAND NEW", "SOLD OUT", "SALE"
  badgeVariant?: LaptopBadgeVariant;
  promotionalText?: string; // e.g., "Free Wireless Mouse"
  // Fields for potential filtering (can be expanded)
  processorType?: string;
  screenSize?: string;
  storageType?: string;
  graphicsType?: string;
  operatingSystem?: string;
}

export const MOCK_LAPTOPS: Laptop[] = [
  {
    id: 'laptop-32',
    name: 'HP Zhan 66 Pro 14 G4, i7 11th Gen, 8GB RAM, 256GB SSD',
    brand: 'HP',
    price: 55000,
    imageUrl: '/WhatsApp Image 2025-09-05 at 13.54.32_6faecb81.jpg',
    dataAiHint: 'hp zhan 66 pro',
    shortDescription: 'Core i7 11th Gen, 8GB RAM, 256GB SSD',
    specs: [
      { key: 'Processor', value: 'Intel Core i7-1165G7 (11th Gen)' },
      { key: 'RAM', value: '8GB DDR4' },
      { key: 'Storage', value: '256GB NVMe SSD' },
      { key: 'Display', value: '14" FHD' },
      { key: 'Features', value: 'Backlit Keyboard, Business Laptop' },
    ],
    stock: 6,
    badgeText: 'NEW',
    badgeVariant: 'new',
    promotionalText: '1 Year Warranty',
    processorType: 'Core i7',
    screenSize: '14"',
    storageType: '256GB SSD',
    graphicsType: 'Intel Iris Xe',
    operatingSystem: 'Windows 11 Pro',
  },
  {
    id: 'laptop-31',
    name: 'HP EliteBook 1030 G7 x360, i7 10th Gen, 16GB RAM, 512GB SSD, Touchscreen',
    brand: 'HP',
    price: 50000,
    imageUrl: '/WhatsApp Image 2025-09-19 at 13.26.02_f3243d59.jpg',
    dataAiHint: 'hp elitebook 1030 g7',
    shortDescription: 'Core i7 10th Gen, 16GB, 512GB SSD, x360 Touchscreen',
    specs: [
      { key: 'Processor', value: 'Intel Core i7-10610U (10th Gen)' },
      { key: 'RAM', value: '16GB DDR4' },
      { key: 'Storage', value: '512GB NVMe SSD' },
      { key: 'Display', value: '13.3" FHD IPS x360 Touchscreen' },
      { key: 'Features', value: 'Backlit Keyboard, Bang & Olufsen Audio, Convertible' },
    ],
    stock: 5,
    badgeText: 'NEW',
    badgeVariant: 'new',
    promotionalText: '1 Year Warranty',
    processorType: 'Core i7',
    screenSize: '13.3"',
    storageType: '512GB SSD',
    graphicsType: 'Integrated Intel UHD',
    operatingSystem: 'Windows 10 Pro',
  },
  {
    id: 'laptop-30',
    name: 'HP EliteBook 830 G8, i7 11th Gen, 16GB RAM, 256GB SSD',
    brand: 'HP',
    price: 40000,
    imageUrl: '/WhatsApp Image 2025-09-24 at 15.38.57_1433bae7.jpg',
    dataAiHint: 'hp elitebook silver',
    shortDescription: 'Core i7 11th Gen, 16GB RAM, 256GB SSD',
    specs: [
        { key: 'Processor', value: 'Intel Core i7-1165G7 (11th Gen)' },
        { key: 'RAM', value: '16GB DDR4' },
        { key: 'Storage', value: '256GB NVMe SSD' },
        { key: 'Display', value: '13.3" FHD IPS' },
        { key: 'Features', value: 'Backlit Keyboard, Bang & Olufsen Audio' },
    ],
    stock: 7,
    badgeText: 'NEW',
    badgeVariant: 'new',
    promotionalText: '1 Year Warranty',
    processorType: 'Core i7',
    screenSize: '13.3"',
    storageType: '256GB SSD',
    graphicsType: 'Intel Iris Xe',
    operatingSystem: 'Windows 11 Pro',
  },
  {
    id: 'laptop-28',
    name: 'HP EliteBook 1030 G3 x360, i7 8th Gen, 16GB RAM, 256GB SSD, Touchscreen',
    brand: 'HP',
    price: 43000,
    imageUrl: '/WhatsApp Image 2025-09-26 at 16.13.44_82edf468.jpg',
    dataAiHint: 'hp elitebook x360',
    shortDescription: 'Core i7 8th Gen, 16GB, 256GB SSD, x360 Touchscreen',
    specs: [
      { key: 'Processor', value: 'Intel Core i7-8550U (8th Gen)' },
      { key: 'RAM', value: '16GB DDR4' },
      { key: 'Storage', value: '256GB NVMe SSD' },
      { key: 'Display', value: '13.3" FHD IPS x360 Touchscreen' },
      { key: 'Features', value: 'Backlit Keyboard, Bang & Olufsen Audio' },
    ],
    stock: 8,
    badgeText: 'HOT DEAL',
    badgeVariant: 'hotdeal',
    promotionalText: '1 Year Warranty',
    processorType: 'Core i7',
    screenSize: '13.3"',
    storageType: '256GB SSD',
    graphicsType: 'Integrated Intel UHD 620',
    operatingSystem: 'Windows 10 Pro',
  },
  {
    id: 'laptop-26',
    name: 'HP EliteBook 830 G7, i5 10th Gen, 8GB RAM, 256GB SSD, Touchscreen',
    brand: 'HP',
    price: 35000,
    originalPrice: 92000,
    imageUrl: '/Hp830g7.jpg',
    dataAiHint: 'hp elitebook silver',
    shortDescription: 'Core i5 10th Gen, 8GB, 256GB SSD, Touchscreen',
    specs: [
      { key: 'Processor', value: 'Intel Core i5-10210U (10th Gen)' },
      { key: 'RAM', value: '8GB DDR4' },
      { key: 'Storage', value: '256GB NVMe SSD' },
      { key: 'Display', value: '13.3" FHD Touchscreen' },
      { key: 'Features', value: 'Backlit Keyboard, Fingerprint Reader' },
    ],
    stock: 15,
    badgeText: 'NEW',
    badgeVariant: 'new',
    promotionalText: '1 Year Warranty',
    processorType: 'Core i5',
    screenSize: '13.3"',
    storageType: '256GB SSD',
    graphicsType: 'Integrated Intel UHD',
    operatingSystem: 'Windows 10 Pro',
  },
  {
    id: 'laptop-27',
    name: 'HP EliteBook 820 G3, i7 6th Gen, 8GB RAM, 256GB SSD',
    brand: 'HP',
    price: 22000,
    imageUrl: '/Hp820G7.jpg',
    dataAiHint: 'hp elitebook silver',
    shortDescription: 'Core i7 6th Gen, 8GB, 256GB SSD',
    specs: [
        { key: 'Processor', value: 'Intel Core i7-6500U (6th Gen)' },
        { key: 'RAM', value: '8GB DDR4' },
        { key: 'Storage', value: '256GB SSD' },
        { key: 'Display', value: '12.5" HD' },
        { key: 'Features', value: 'Backlit Keyboard' },
    ],
    stock: 20,
    badgeText: 'NEW',
    badgeVariant: 'new',
    promotionalText: '1 Year Warranty',
    processorType: 'Core i7',
    screenSize: '12.5"',
    storageType: '256GB SSD',
    graphicsType: 'Integrated Intel HD 520',
    operatingSystem: 'Windows 10 Pro',
  },
  {
    id: 'laptop-29',
    name: 'HP 840 G5, i5 8th Gen, 8GB RAM, 256GB SSD',
    brand: 'HP',
    price: 25000,
    imageUrl: '/WhatsApp Image 2025-09-26 at 15.41.44_01cbe24e.jpg',
    dataAiHint: 'hp elitebook silver',
    shortDescription: 'Core i5 8th Gen, 8GB, 256GB SSD',
    specs: [
        { key: 'Processor', value: 'Intel Core i5-8250U (8th Gen)' },
        { key: 'RAM', value: '8GB DDR4' },
        { key: 'Storage', value: '256GB NVMe SSD' },
        { key: 'Display', value: '14" FHD IPS' },
        { key: 'Features', value: 'Backlit Keyboard, Fingerprint Reader' },
    ],
    stock: 10,
    badgeText: 'NEW',
    badgeVariant: 'new',
    promotionalText: '1 Year Warranty',
    processorType: 'Core i5',
    screenSize: '14"',
    storageType: '256GB SSD',
    graphicsType: 'Integrated Intel UHD 620',
    operatingSystem: 'Windows 10 Pro',
  },
  {
    id: 'accessory-1',
    name: '512GB SSD Hard Disk',
    brand: 'Accessory',
    price: 8500,
    imageUrl: '/WhatsApp Image 2025-09-05 at 13.54.50_b821f427.jpg',
    dataAiHint: '512gb ssd',
    shortDescription: 'High-speed 512GB Solid State Drive',
    specs: [
      { key: 'Capacity', value: '512GB' },
      { key: 'Type', value: 'SSD (Solid State Drive)' },
      { key: 'Compatibility', value: 'Laptops & Desktops' },
    ],
    stock: 20,
    badgeText: 'UPGRADE',
    badgeVariant: 'new',
    promotionalText: 'Boost your speed!',
    storageType: '512GB SSD',
  },
  {
    id: 'accessory-2',
    name: 'TYPE C TO HDTV 5 IN 1 ADAPTER',
    brand: 'Accessory',
    price: 1500,
    imageUrl: '/WhatsApp Image 2025-09-05 at 13.55.02_bf51d633.jpg',
    dataAiHint: 'usb-c adapter',
    shortDescription: '5-in-1 USB-C to HDMI Multiport Adapter',
    specs: [
        { key: 'Ports', value: 'HDMI, USB 3.0, SD/TF Card Reader, USB-C PD' },
        { key: 'Compatibility', value: 'MacBook, Dell XPS, HP Spectre, etc.' },
    ],
    stock: 30,
    badgeText: 'NEW',
    badgeVariant: 'new',
    promotionalText: 'Connect everything!',
  },
  {
    id: 'accessory-3',
    name: 'HP Wired Mouse X500',
    brand: 'HP',
    price: 350,
    imageUrl: '/WhatsApp Image 2025-09-05 at 13.55.25_6e083999.jpg',
    dataAiHint: 'hp wired mouse',
    shortDescription: 'Reliable wired USB mouse',
    specs: [
      { key: 'Connectivity', value: 'Wired USB' },
      { key: 'Compatibility', value: 'Windows & macOS' },
    ],
    stock: 50,
    badgeText: 'ACCESSORY',
    badgeVariant: 'secondary',
  },
  {
    id: 'accessory-4',
    name: 'Logitech Mouse M185',
    brand: 'Logitech',
    price: 1200,
    imageUrl: '/WhatsApp Image 2025-09-05 at 13.55.44_c35d8705.jpg',
    dataAiHint: 'logitech mouse',
    shortDescription: 'Reliable wireless mouse',
    specs: [
      { key: 'Connectivity', value: 'Wireless USB Receiver' },
      { key: 'Compatibility', value: 'Windows & macOS' },
    ],
    stock: 40,
    badgeText: 'ACCESSORY',
    badgeVariant: 'secondary',
  },
  {
    id: 'accessory-5',
    name: 'Logitech Headsets H340',
    brand: 'Logitech',
    price: 4500,
    imageUrl: '/WhatsApp Image 2025-09-05 at 13.55.56_f043d585.jpg',
    dataAiHint: 'logitech headset',
    shortDescription: 'Clear digital audio for calls and music',
    specs: [
      { key: 'Connectivity', value: 'Wired USB' },
      { key: 'Features', value: 'Noise-canceling microphone' },
    ],
    stock: 25,
    badgeText: 'ACCESSORY',
    badgeVariant: 'secondary',
  },
  {
    id: 'accessory-6',
    name: 'Logitech M170 Mouse',
    brand: 'Logitech',
    price: 1300,
    imageUrl: '/WhatsApp Image 2025-09-05 at 13.56.10_52ffee68.jpg',
    dataAiHint: 'logitech mouse wireless',
    shortDescription: 'Wireless mouse with reliable connectivity',
    specs: [
      { key: 'Connectivity', value: 'Wireless USB Receiver' },
      { key: 'Compatibility', value: 'Windows & macOS' },
    ],
    stock: 45,
    badgeText: 'ACCESSORY',
    badgeVariant: 'secondary',
  },
  {
    id: 'accessory-7',
    name: 'Logitech M171 Mouse',
    brand: 'Logitech',
    price: 1100,
    imageUrl: '/WhatsApp Image 2025-09-05 at 13.56.18_85468525.jpg',
    dataAiHint: 'logitech mouse black',
    shortDescription: 'Plug and play wireless mouse',
    specs: [
        { key: 'Connectivity', value: 'Wireless USB Receiver' },
        { key: 'Compatibility', value: 'Windows & macOS' },
    ],
    stock: 50,
    badgeText: 'ACCESSORY',
    badgeVariant: 'secondary',
  },
  {
    id: 'laptop-15',
    name: 'Apple MacBook Pro 14 M2 Pro, 16GB RAM, 512GB SSD',
    brand: 'Apple',
    price: 249999,
    imageUrl: 'https://images.unsplash.com/photo-1569770218135-bea267ed7e84',
    dataAiHint: 'macbook pro spacegrey',
    shortDescription: 'M2 Pro, 16GB RAM, 512GB SSD',
    specs: [
      { key: 'Processor', value: 'Apple M2 Pro Chip (10-core CPU, 16-core GPU)' },
      { key: 'RAM', value: '16GB Unified Memory' },
      { key: 'Storage', value: '512GB SSD' },
      { key: 'Display', value: '14.2" Liquid Retina XDR' },
    ],
    stock: 6,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    promotionalText: 'Pro Power',
    processorType: 'Apple M2 Pro',
    screenSize: '14.2"',
    storageType: '512GB SSD',
    graphicsType: 'Integrated 16-core GPU',
    operatingSystem: 'macOS'
  },
];
