
export interface LaptopSpec {
  key: string;
  value: string;
}

export type LaptopBadgeVariant = 'default' | 'secondary' | 'destructive' | 'outline' | 'hotdeal' | 'new';

export interface Laptop {
  id: string;
  name: string;
  brand: string;
  price: number;
  originalPrice?: number; // For strikethrough pricing
  imageUrl: string;
  dataAiHint?: string;
  shortDescription: string; // This will be used as the main spec line below title
  specs: LaptopSpec[]; // Detailed specs, maybe for a detail page later
  stock: number;
  badgeText?: string; // e.g., "BRAND NEW", "SOLD OUT", "SALE"
  badgeVariant?: LaptopBadgeVariant;
  promotionalText?: string; // e.g., "Free Wireless Mouse"
  // Fields for potential filtering (can be expanded)
  processorType?: string;
  screenSize?: string;
  storageType?: string;
  graphicsType?: string;
  operatingSystem?: string;
}

export const MOCK_LAPTOPS: Laptop[] = [
  {
    id: 'laptop-32',
    name: 'HP Zhan 66 Pro 14 G4, i7 11th Gen, 8GB RAM, 256GB SSD',
    brand: 'HP',
    price: 55000,
    imageUrl: '/WhatsApp Image 2025-09-05 at 13.54.32_6faecb81.jpg',
    dataAiHint: 'hp zhan 66 pro',
    shortDescription: 'Core i7 11th Gen, 8GB RAM, 256GB SSD',
    specs: [
      { key: 'Processor', value: 'Intel Core i7-1165G7 (11th Gen)' },
      { key: 'RAM', value: '8GB DDR4' },
      { key: 'Storage', value: '256GB NVMe SSD' },
      { key: 'Display', value: '14" FHD' },
      { key: 'Features', value: 'Backlit Keyboard, Business Laptop' },
    ],
    stock: 6,
    badgeText: 'NEW',
    badgeVariant: 'new',
    promotionalText: '1 Year Warranty',
    processorType: 'Core i7',
    screenSize: '14"',
    storageType: '256GB SSD',
    graphicsType: 'Intel Iris Xe',
    operatingSystem: 'Windows 11 Pro',
  },
  {
    id: 'laptop-31',
    name: 'HP EliteBook 1030 G7 x360, i7 10th Gen, 16GB RAM, 512GB SSD, Touchscreen',
    brand: 'HP',
    price: 50000,
    imageUrl: '/WhatsApp Image 2025-09-19 at 13.26.02_f3243d59.jpg',
    dataAiHint: 'hp elitebook 1030 g7',
    shortDescription: 'Core i7 10th Gen, 16GB, 512GB SSD, x360 Touchscreen',
    specs: [
      { key: 'Processor', value: 'Intel Core i7-10610U (10th Gen)' },
      { key: 'RAM', value: '16GB DDR4' },
      { key: 'Storage', value: '512GB NVMe SSD' },
      { key: 'Display', value: '13.3" FHD IPS x360 Touchscreen' },
      { key: 'Features', value: 'Backlit Keyboard, Bang & Olufsen Audio, Convertible' },
    ],
    stock: 5,
    badgeText: 'NEW',
    badgeVariant: 'new',
    promotionalText: '1 Year Warranty',
    processorType: 'Core i7',
    screenSize: '13.3"',
    storageType: '512GB SSD',
    graphicsType: 'Integrated Intel UHD',
    operatingSystem: 'Windows 10 Pro',
  },
  {
    id: 'laptop-30',
    name: 'HP EliteBook 830 G8, i7 11th Gen, 16GB RAM, 256GB SSD',
    brand: 'HP',
    price: 40000,
    imageUrl: '/WhatsApp Image 2025-09-24 at 15.38.57_1433bae7.jpg',
    dataAiHint: 'hp elitebook silver',
    shortDescription: 'Core i7 11th Gen, 16GB RAM, 256GB SSD',
    specs: [
        { key: 'Processor', value: 'Intel Core i7-1165G7 (11th Gen)' },
        { key: 'RAM', value: '16GB DDR4' },
        { key: 'Storage', value: '256GB NVMe SSD' },
        { key: 'Display', value: '13.3" FHD IPS' },
        { key: 'Features', value: 'Backlit Keyboard, Bang & Olufsen Audio' },
    ],
    stock: 7,
    badgeText: 'NEW',
    badgeVariant: 'new',
    promotionalText: '1 Year Warranty',
    processorType: 'Core i7',
    screenSize: '13.3"',
    storageType: '256GB SSD',
    graphicsType: 'Intel Iris Xe',
    operatingSystem: 'Windows 11 Pro',
  },
  {
    id: 'laptop-28',
    name: 'HP EliteBook 1030 G3 x360, i7 8th Gen, 16GB RAM, 256GB SSD, Touchscreen',
    brand: 'HP',
    price: 43000,
    imageUrl: '/WhatsApp Image 2025-09-26 at 16.13.44_82edf468.jpg',
    dataAiHint: 'hp elitebook x360',
    shortDescription: 'Core i7 8th Gen, 16GB, 256GB SSD, x360 Touchscreen',
    specs: [
      { key: 'Processor', value: 'Intel Core i7-8550U (8th Gen)' },
      { key: 'RAM', value: '16GB DDR4' },
      { key: 'Storage', value: '256GB NVMe SSD' },
      { key: 'Display', value: '13.3" FHD IPS x360 Touchscreen' },
      { key: 'Features', value: 'Backlit Keyboard, Bang & Olufsen Audio' },
    ],
    stock: 8,
    badgeText: 'HOT DEAL',
    badgeVariant: 'hotdeal',
    promotionalText: '1 Year Warranty',
    processorType: 'Core i7',
    screenSize: '13.3"',
    storageType: '256GB SSD',
    graphicsType: 'Integrated Intel UHD 620',
    operatingSystem: 'Windows 10 Pro',
  },
  {
    id: 'laptop-26',
    name: 'HP EliteBook 830 G7, i5 10th Gen, 8GB RAM, 256GB SSD, Touchscreen',
    brand: 'HP',
    price: 35000,
    originalPrice: 92000,
    imageUrl: '/Hp830g7.jpg',
    dataAiHint: 'hp elitebook silver',
    shortDescription: 'Core i5 10th Gen, 8GB, 256GB SSD, Touchscreen',
    specs: [
      { key: 'Processor', value: 'Intel Core i5-10210U (10th Gen)' },
      { key: 'RAM', value: '8GB DDR4' },
      { key: 'Storage', value: '256GB NVMe SSD' },
      { key: 'Display', value: '13.3" FHD Touchscreen' },
      { key: 'Features', value: 'Backlit Keyboard, Fingerprint Reader' },
    ],
    stock: 15,
    badgeText: 'NEW',
    badgeVariant: 'new',
    promotionalText: '1 Year Warranty',
    processorType: 'Core i5',
    screenSize: '13.3"',
    storageType: '256GB SSD',
    graphicsType: 'Integrated Intel UHD',
    operatingSystem: 'Windows 10 Pro',
  },
  {
    id: 'laptop-27',
    name: 'HP EliteBook 820 G3, i7 6th Gen, 8GB RAM, 256GB SSD',
    brand: 'HP',
    price: 22000,
    imageUrl: '/Hp820G7.jpg',
    dataAiHint: 'hp elitebook silver',
    shortDescription: 'Core i7 6th Gen, 8GB, 256GB SSD',
    specs: [
        { key: 'Processor', value: 'Intel Core i7-6500U (6th Gen)' },
        { key: 'RAM', value: '8GB DDR4' },
        { key: 'Storage', value: '256GB SSD' },
        { key: 'Display', value: '12.5" HD' },
        { key: 'Features', value: 'Backlit Keyboard' },
    ],
    stock: 20,
    badgeText: 'NEW',
    badgeVariant: 'new',
    promotionalText: '1 Year Warranty',
    processorType: 'Core i7',
    screenSize: '12.5"',
    storageType: '256GB SSD',
    graphicsType: 'Integrated Intel HD 520',
    operatingSystem: 'Windows 10 Pro',
  },
  {
    id: 'laptop-29',
    name: 'HP 840 G5, i5 8th Gen, 8GB RAM, 256GB SSD',
    brand: 'HP',
    price: 25000,
    imageUrl: '/WhatsApp Image 2025-09-26 at 15.41.44_01cbe24e.jpg',
    dataAiHint: 'hp elitebook silver',
    shortDescription: 'Core i5 8th Gen, 8GB, 256GB SSD',
    specs: [
        { key: 'Processor', value: 'Intel Core i5-8250U (8th Gen)' },
        { key: 'RAM', value: '8GB DDR4' },
        { key: 'Storage', value: '256GB NVMe SSD' },
        { key: 'Display', value: '14" FHD IPS' },
        { key: 'Features', value: 'Backlit Keyboard, Fingerprint Reader' },
    ],
    stock: 10,
    badgeText: 'NEW',
    badgeVariant: 'new',
    promotionalText: '1 Year Warranty',
    processorType: 'Core i5',
    screenSize: '14"',
    storageType: '256GB SSD',
    graphicsType: 'Integrated Intel UHD 620',
    operatingSystem: 'Windows 10 Pro',
  },
  {
    id: 'accessory-1',
    name: '512GB SSD Hard Disk',
    brand: 'Accessory',
    price: 8500,
    imageUrl: '/WhatsApp Image 2025-09-05 at 13.54.50_b821f427.jpg',
    dataAiHint: '512gb ssd',
    shortDescription: 'High-speed 512GB Solid State Drive',
    specs: [
      { key: 'Capacity', value: '512GB' },
      { key: 'Type', value: 'SSD (Solid State Drive)' },
      { key: 'Compatibility', value: 'Laptops & Desktops' },
    ],
    stock: 20,
    badgeText: 'UPGRADE',
    badgeVariant: 'new',
    promotionalText: 'Boost your speed!',
    storageType: '512GB SSD',
  },
  {
    id: 'accessory-2',
    name: 'TYPE C TO HDTV 5 IN 1 ADAPTER',
    brand: 'Accessory',
    price: 1500,
    imageUrl: '/WhatsApp Image 2025-09-05 at 13.55.02_bf51d633.jpg',
    dataAiHint: 'usb-c adapter',
    shortDescription: '5-in-1 USB-C to HDMI Multiport Adapter',
    specs: [
        { key: 'Ports', value: 'HDMI, USB 3.0, SD/TF Card Reader, USB-C PD' },
        { key: 'Compatibility', value: 'MacBook, Dell XPS, HP Spectre, etc.' },
    ],
    stock: 30,
    badgeText: 'NEW',
    badgeVariant: 'new',
    promotionalText: 'Connect everything!',
  },
  {
    id: 'laptop-10',
    name: 'Apple MacBook Air M1, 8GB RAM, 256GB SSD',
    brand: 'Apple',
    price: 109999,
    originalPrice: 115000,
    imageUrl: 'https://nairobicomputershop.co.ke/media/products/2022/07/MC_1.jpg',
    dataAiHint: 'macbook air silver',
    shortDescription: 'M1 Chip, 8GB RAM, 256GB SSD',
    specs: [
      { key: 'Processor', value: 'Apple M1 Chip' },
      { key: 'RAM', value: '8GB Unified Memory' },
      { key: 'Storage', value: '256GB SSD' },
      { key: 'Display', value: '13.3" Retina' },
    ],
    stock: 10,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    processorType: 'Apple M1',
    screenSize: '13.3"',
    storageType: '256GB SSD',
    graphicsType: 'Integrated 7-core GPU',
    operatingSystem: 'macOS'
  },
  {
    id: 'laptop-11',
    name: 'HP Pavilion 15, Ryzen 5, 8GB RAM, 512GB SSD',
    brand: 'HP',
    price: 68500,
    imageUrl: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed',
    dataAiHint: 'hp pavilion blue',
    shortDescription: 'Ryzen 5, 8GB RAM, 512GB SSD',
    specs: [
      { key: 'Processor', value: 'AMD Ryzen 5 5500U' },
      { key: 'RAM', value: '8GB DDR4' },
      { key: 'Storage', value: '512GB NVMe SSD' },
      { key: 'Display', value: '15.6" FHD IPS' },
    ],
    stock: 18,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    promotionalText: 'Includes Backpack',
    processorType: 'Ryzen 5',
    screenSize: '15.6"',
    storageType: '512GB SSD',
    graphicsType: 'AMD Radeon Graphics',
    operatingSystem: 'Windows 11'
  },
  {
    id: 'laptop-12',
    name: 'Asus VivoBook 14, Core i5, 12GB RAM, 512GB SSD',
    brand: 'Asus',
    price: 72000,
    originalPrice: 75000,
    imageUrl: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9',
    dataAiHint: 'asus vivobook grey',
    shortDescription: 'Core i5, 12GB RAM, 512GB SSD',
    specs: [
      { key: 'Processor', value: 'Intel Core i5-1135G7' },
      { key: 'RAM', value: '12GB DDR4' },
      { key: 'Storage', value: '512GB SSD' },
      { key: 'Display', value: '14" FHD NanoEdge' },
    ],
    stock: 8,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    processorType: 'Core i5',
    screenSize: '14"',
    storageType: '512GB SSD',
    graphicsType: 'Intel Iris Xe',
    operatingSystem: 'Windows 10'
  },
  {
    id: 'laptop-13',
    name: 'Lenovo Legion 5, Ryzen 7, 16GB RAM, 1TB SSD, RTX 3060',
    brand: 'Lenovo',
    price: 145000,
    imageUrl: 'https://images.unsplash.com/photo-1618225042443-a614b19b6343',
    dataAiHint: 'lenovo legion gaming',
    shortDescription: 'Ryzen 7, RTX 3060, 16GB RAM',
    specs: [
      { key: 'Processor', value: 'AMD Ryzen 7 5800H' },
      { key: 'RAM', value: '16GB DDR4' },
      { key: 'Storage', value: '1TB NVMe SSD' },
      { key: 'Display', value: '15.6" FHD 165Hz' },
      { key: 'Graphics', value: 'NVIDIA GeForce RTX 3060 6GB' },
    ],
    stock: 5,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    promotionalText: 'RGB Keyboard',
    processorType: 'Ryzen 7',
    screenSize: '15.6"',
    storageType: '1TB SSD',
    graphicsType: 'NVIDIA RTX 3060',
    operatingSystem: 'Windows 11'
  },
  {
    id: 'laptop-14',
    name: 'Dell XPS 13, Core i7, 16GB RAM, 512GB SSD',
    brand: 'Dell',
    price: 159999,
    imageUrl: 'https://images.unsplash.com/photo-1542393545-10f5cde2c810',
    dataAiHint: 'dell xps silver',
    shortDescription: 'Core i7, 16GB RAM, 512GB SSD, UHD+',
    specs: [
      { key: 'Processor', value: 'Intel Core i7-1260P' },
      { key: 'RAM', value: '16GB LPDDR5' },
      { key: 'Storage', value: '512GB NVMe SSD' },
      { key: 'Display', value: '13.4" FHD+ InfinityEdge' },
    ],
    stock: 7,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    processorType: 'Core i7',
    screenSize: '13.4"',
    storageType: '512GB SSD',
    graphicsType: 'Intel Iris Xe',
    operatingSystem: 'Windows 11 Pro'
  },
  {
    id: 'laptop-15',
    name: 'Apple MacBook Pro 14 M2 Pro, 16GB RAM, 512GB SSD',
    brand: 'Apple',
    price: 249999,
    imageUrl: 'https://images.unsplash.com/photo-1569770218135-bea267ed7e84',
    dataAiHint: 'macbook pro spacegrey',
    shortDescription: 'M2 Pro, 16GB RAM, 512GB SSD',
    specs: [
      { key: 'Processor', value: 'Apple M2 Pro Chip (10-core CPU, 16-core GPU)' },
      { key: 'RAM', value: '16GB Unified Memory' },
      { key: 'Storage', value: '512GB SSD' },
      { key: 'Display', value: '14.2" Liquid Retina XDR' },
    ],
    stock: 6,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    promotionalText: 'Pro Power',
    processorType: 'Apple M2 Pro',
    screenSize: '14.2"',
    storageType: '512GB SSD',
    graphicsType: 'Integrated 16-core GPU',
    operatingSystem: 'macOS'
  },
  {
    id: 'laptop-16',
    name: 'Asus ROG Zephyrus G14, Ryzen 9, 16GB RAM, 1TB SSD, RTX 3050Ti',
    brand: 'Asus',
    price: 165000,
    originalPrice: 175000,
    imageUrl: 'https://images.unsplash.com/photo-1643448981657-3a443919b35b',
    dataAiHint: 'asus rog white',
    shortDescription: 'Ryzen 9, RTX 3050Ti, AniMe Matrix',
    specs: [
      { key: 'Processor', value: 'AMD Ryzen 9 6900HS' },
      { key: 'RAM', value: '16GB DDR5' },
      { key: 'Storage', value: '1TB PCIe 4.0 SSD' },
      { key: 'Display', value: '14" QHD+ 120Hz Pantone Validated' },
      { key: 'Graphics', value: 'NVIDIA GeForce RTX 3050 Ti 4GB' },
    ],
    stock: 9,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    promotionalText: 'AniMe Matrix Display',
    processorType: 'Ryzen 9',
    screenSize: '14"',
    storageType: '1TB SSD',
    graphicsType: 'NVIDIA RTX 3050Ti',
    operatingSystem: 'Windows 11'
  },
  {
    id: 'laptop-17',
    name: 'HP Envy x360 13, Core i5, 8GB RAM, 512GB SSD',
    brand: 'HP',
    price: 98000,
    imageUrl: 'https://images.unsplash.com/photo-1616443185387-4a41334b0d50',
    dataAiHint: 'hp envy convertible',
    shortDescription: 'Convertible, Core i5, 8GB RAM, 512GB SSD',
    specs: [
      { key: 'Processor', value: 'Intel Core i5-1230U' },
      { key: 'RAM', value: '8GB DDR4' },
      { key: 'Storage', value: '512GB NVMe SSD' },
      { key: 'Display', value: '13.3" FHD Touchscreen OLED' },
    ],
    stock: 11,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    processorType: 'Core i5',
    screenSize: '13.3"',
    storageType: '512GB SSD',
    graphicsType: 'Intel Iris Xe',
    operatingSystem: 'Windows 11'
  },
  {
    id: 'laptop-18',
    name: 'Lenovo ThinkPad E14 Gen 3, Ryzen 5, 16GB RAM, 512GB SSD',
    brand: 'Lenovo',
    price: 85000,
    imageUrl: 'https://plus.unsplash.com/premium_photo-1679397828082-93856237c569',
    dataAiHint: 'lenovo thinkpad black',
    shortDescription: 'Ryzen 5, 16GB RAM, Business Laptop',
    specs: [
      { key: 'Processor', value: 'AMD Ryzen 5 5600U' },
      { key: 'RAM', value: '16GB DDR4' },
      { key: 'Storage', value: '512GB NVMe SSD' },
      { key: 'Display', value: '14" FHD Anti-glare' },
    ],
    stock: 14,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    promotionalText: 'ThinkShield Security',
    processorType: 'Ryzen 5',
    screenSize: '14"',
    storageType: '512GB SSD',
    graphicsType: 'AMD Radeon Graphics',
    operatingSystem: 'Windows 10 Pro'
  },
  {
    id: 'laptop-19',
    name: 'Dell Latitude 7420, Core i5, 16GB RAM, 256GB SSD',
    brand: 'Dell',
    price: 115000,
    originalPrice: 125000,
    imageUrl: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2',
    dataAiHint: 'dell latitude business',
    shortDescription: 'Business, Core i5, 16GB RAM, Lightweight',
    specs: [
      { key: 'Processor', value: 'Intel Core i5-1145G7 vPro' },
      { key: 'RAM', value: '16GB DDR4' },
      { key: 'Storage', value: '256GB NVMe SSD' },
      { key: 'Display', value: '14" FHD Anti-glare' },
    ],
    stock: 10,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    processorType: 'Core i5',
    screenSize: '14"',
    storageType: '256GB SSD',
    graphicsType: 'Intel Iris Xe',
    operatingSystem: 'Windows 10 Pro'
  },
  {
    id: 'laptop-20',
    name: 'Asus ZenBook Duo 14, Core i7, 16GB RAM, 1TB SSD, ScreenPad Plus',
    brand: 'Asus',
    price: 199999,
    imageUrl: 'https://images.unsplash.com/photo-1606220863836-c69224b75245',
    dataAiHint: 'asus zenbook duo',
    shortDescription: 'Dual Screen, Core i7, 16GB RAM, 1TB SSD',
    specs: [
      { key: 'Processor', value: 'Intel Core i7-12700H' },
      { key: 'RAM', value: '16GB LPDDR5' },
      { key: 'Storage', value: '1TB PCIe 4.0 SSD' },
      { key: 'Display', value: '14.5" 2.8K OLED Touch + 12.7" ScreenPad Plus' },
      { key: 'Graphics', value: 'Intel Iris Xe' },
    ],
    stock: 4,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    promotionalText: 'Stylus Included',
    processorType: 'Core i7',
    screenSize: '14.5"',
    storageType: '1TB SSD',
    graphicsType: 'Intel Iris Xe',
    operatingSystem: 'Windows 11 Pro'
  },
  {
    id: 'laptop-21',
    name: 'HP Spectre x360 14, Core i7, 16GB RAM, 1TB SSD, OLED',
    brand: 'HP',
    price: 185000,
    imageUrl: 'https://images.unsplash.com/photo-1616443185387-4a41334b0d50',
    dataAiHint: 'hp spectre gold',
    shortDescription: 'Convertible, Core i7, OLED, 1TB SSD',
    specs: [
      { key: 'Processor', value: 'Intel Core i7-1355U' },
      { key: 'RAM', value: '16GB LPDDR4x' },
      { key: 'Storage', value: '1TB NVMe SSD' },
      { key: 'Display', value: '13.5" 3K2K OLED Touchscreen' },
    ],
    stock: 6,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    processorType: 'Core i7',
    screenSize: '13.5"',
    storageType: '1TB SSD',
    graphicsType: 'Intel Iris Xe',
    operatingSystem: 'Windows 11 Home'
  },
  {
    id: 'laptop-22',
    name: 'Lenovo Yoga Slim 7 Pro, Ryzen 7, 16GB RAM, 512GB SSD',
    brand: 'Lenovo',
    price: 110000,
    originalPrice: 120000,
    imageUrl: 'https://images.unsplash.com/photo-1602081036496-c1483b3815fe',
    dataAiHint: 'lenovo yoga slim',
    shortDescription: 'Ryzen 7, 16GB RAM, QHD Display',
    specs: [
      { key: 'Processor', value: 'AMD Ryzen 7 5800HS' },
      { key: 'RAM', value: '16GB DDR4' },
      { key: 'Storage', value: '512GB NVMe SSD' },
      { key: 'Display', value: '14" 2.8K QHD IPS 90Hz' },
    ],
    stock: 10,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    promotionalText: 'Lightweight Design',
    processorType: 'Ryzen 7',
    screenSize: '14"',
    storageType: '512GB SSD',
    graphicsType: 'AMD Radeon Graphics',
    operatingSystem: 'Windows 11'
  },
  {
    id: 'laptop-23',
    name: 'Microsoft Surface Laptop 5 13.5", Core i5, 8GB RAM, 256GB SSD',
    brand: 'Microsoft',
    price: 125000,
    imageUrl: 'https://images.unsplash.com/photo-1662010022067-5a4014c5b36e',
    dataAiHint: 'surface laptop platinum',
    shortDescription: 'Core i5, 8GB RAM, PixelSense Display',
    specs: [
      { key: 'Processor', value: 'Intel Core i5-1235U' },
      { key: 'RAM', value: '8GB LPDDR5x' },
      { key: 'Storage', value: '256GB SSD' },
      { key: 'Display', value: '13.5” PixelSense Touchscreen (2256 x 1504)' },
    ],
    stock: 9,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    processorType: 'Core i5',
    screenSize: '13.5"',
    storageType: '256GB SSD',
    graphicsType: 'Intel Iris Xe',
    operatingSystem: 'Windows 11'
  },
  {
    id: 'laptop-24',
    name: 'Acer Aspire 5, Core i5, 8GB RAM, 512GB SSD, MX450',
    brand: 'Acer',
    price: 65000,
    imageUrl: 'https://images.unsplash.com/photo-1589561084212-7235b0445d44',
    dataAiHint: 'acer aspire silver',
    shortDescription: 'Core i5, 8GB RAM, NVIDIA MX450',
    specs: [
      { key: 'Processor', value: 'Intel Core i5-1135G7' },
      { key: 'RAM', value: '8GB DDR4' },
      { key: 'Storage', value: '512GB NVMe SSD' },
      { key: 'Display', value: '15.6" FHD IPS' },
      { key: 'Graphics', value: 'NVIDIA GeForce MX450 2GB' },
    ],
    stock: 15,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    processorType: 'Core i5',
    screenSize: '15.6"',
    storageType: '512GB SSD',
    graphicsType: 'NVIDIA MX450',
    operatingSystem: 'Windows 10'
  },
  {
    id: 'laptop-25',
    name: 'Samsung Galaxy Book3 Pro 16", Core i7, 16GB RAM, 1TB SSD',
    brand: 'Samsung',
    price: 170000,
    imageUrl: 'https://images.unsplash.com/photo-1676813333332-9df75f1b2b3a',
    dataAiHint: 'samsung galaxybook',
    shortDescription: 'AMOLED 3K, Core i7, 16GB RAM, 1TB SSD',
    specs: [
      { key: 'Processor', value: 'Intel Core i7-1360P' },
      { key: 'RAM', value: '16GB LPDDR5' },
      { key: 'Storage', value: '1TB NVMe SSD' },
      { key: 'Display', value: '16" Dynamic AMOLED 2X (2880 x 1800) 120Hz' },
    ],
    stock: 7,
    badgeText: 'SALE',
    badgeVariant: 'hotdeal',
    promotionalText: 'Slim & Light',
    processorType: 'Core i7',
    screenSize: '16"',
    storageType: '1TB SSD',
    graphicsType: 'Intel Iris Xe',
    operatingSystem: 'Windows 11'
  },
];

    

    

    

    


      

    

    