
import type { Project } from "@/components/projects/types";

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-24',
    title: 'ABC Deliveries',
    description: 'Triple-interface food ecosystem for customers, merchants, and logistics teams.',
    longDescription: 'Engineered a complex multi-interface ecosystem that synchronizes real-time logistics. The platform features three distinct portals: a user-friendly customer ordering app, a robust merchant dashboard for restaurant owners, and a high-performance rider coordination system. Integrated with M-Pesa for instant payments and real-time tracking to ensure absolute reliability in the Kenyan food delivery market.',
    image: 'https://images.unsplash.com/photo-1526367790999-0150786486a9?q=80&w=2070&auto=format&fit=crop',
    dataAiHint: 'delivery scooter box',
    techStack: ['Go (Backend)', 'Dart / Flutter', 'Next.js', 'Redis', 'PostgreSQL'],
    liveUrl: 'https://abcdeliveries.vercel.app/',
    projectType: 'Systems',
    status: 'Sold',
  },
  {
    id: 'proj-23',
    title: 'Patrick Osoi',
    description: 'High-impact digital presence for elite activism and political leadership.',
    longDescription: 'Developed a high-impact personal brand platform for Patrick Osoi, a prominent Kenyan activist and politician. The site is engineered for high-volume traffic, secure communication, and sophisticated narrative-driven engagement, reflecting the authority and mission of his public office.',
    image: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?q=80&w=2070&auto=format&fit=crop',
    dataAiHint: 'political podium speaker',
    techStack: ['Python / Django', 'Next.js', 'PostgreSQL', 'Vercel SEO'],
    liveUrl: 'https://www.patrickosoi.co.ke/',
    projectType: 'Web',
    status: 'Sold',
  },
  {
    id: 'proj-22',
    title: 'Henry Adeeya',
    description: 'High-end personal brand architecture for strategic leadership and consultancy.',
    longDescription: 'Designed and developed a premium personal portfolio for Henry Adeeya, a leading strategic consultant. The platform features an elegant, minimalist design optimized for authority-building and direct professional engagement. It showcases a refined user experience tailored for corporate leadership.',
    image: 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?q=80&w=2072&auto=format&fit=crop',
    dataAiHint: 'professional minimalist portfolio',
    techStack: ['Next.js', 'Framer Motion', 'TypeScript', 'Node.js'],
    liveUrl: 'https://www.henryadeeya.com/',
    projectType: 'Web',
    status: 'Sold',
  },
  {
    id: 'proj-21',
    title: 'YEDNA Corporate Document Generator',
    description: 'Advanced automated system for generating professional corporate documents and legal templates.',
    longDescription: 'Developed YEDNA, a high-performance document automation engine. The platform streamlines corporate workflows by allowing users to generate complex, brand-consistent legal and business documents instantly through an intuitive cloud interface. Features real-time template editing and secure PDF processing.',
    image: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?q=80&w=2070&auto=format&fit=crop',
    dataAiHint: 'office documents paperwork',
    techStack: ['Go', 'Next.js', 'AWS Lambda', 'DynamoDB'],
    liveUrl: 'https://yedna.vercel.app/',
    projectType: 'Systems',
    status: 'Sold',
  },
  {
    id: 'proj-20',
    title: 'Prime Ink Technologies',
    description: 'Specialized e-commerce architecture for premium printing hardware and consumables.',
    longDescription: 'Developed a robust e-commerce platform for Prime Ink Technologies, focusing on technical product categorization for printers, toners, and ink. The system features a streamlined search experience, secure payment integration, and a mobile-first interface optimized for corporate procurement.',
    image: 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?q=80&w=2070&auto=format&fit=crop',
    dataAiHint: 'office printer tech',
    techStack: ['Python', 'Next.js', 'M-Pesa API', 'ElasticSearch'],
    liveUrl: 'https://prime-ink-technologies.vercel.app/',
    projectType: 'Web',
    status: 'Sold',
  },
  {
    id: 'proj-19',
    title: 'KEJAINN Cloud Tenant Management',
    description: 'Comprehensive cloud system for automated rent tracking and property operations.',
    longDescription: 'Engineered a high-performance tenant management solution tailored for the Kenyan real estate market. The system automates rent collection via M-Pesa integration, manages occupancy data, and tracks maintenance requests through a secure cloud dashboard. Designed for scalability and absolute data integrity.',
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?q=80&w=2073&auto=format&fit=crop',
    dataAiHint: 'real estate management',
    techStack: ['Java / Spring Boot', 'React', 'M-Pesa API', 'MySQL'],
    liveUrl: 'https://kejainncloud-3v7v.vercel.app/',
    projectType: 'Systems',
    status: 'Sold',
  },
  {
    id: 'proj-18',
    title: 'Trading Bot',
    description: 'A high-performance trading bot featuring real-time market data, secure transactions, and intuitive analytics.',
    longDescription: 'Engineered a sophisticated cryptocurrency and forex trading bot. The system integrates real-time price feeds via WebSockets, secure wallet management, and a high-performance order matching engine. Designed with a focus on low-latency execution and professional-grade charting tools to empower modern traders in the digital economy.',
    image: 'https://images.unsplash.com/photo-1633156191730-2ed37ca602dc?q=80&w=2070&auto=format&fit=crop',
    dataAiHint: 'trading data terminal',
    techStack: ['Go', 'Python (ML)', 'WebSockets', 'React', 'TimescaleDB'],
    liveUrl: 'https://crypro-kenya.vercel.app/',
    projectType: 'Systems',
    status: 'Sold',
  },
  {
    id: 'proj-17',
    title: 'National Intelligence Voting Platform',
    description: 'An advanced digital intelligence system designed for secure national-level online voting and geo-spatial data visualization.',
    longDescription: 'Engineered a highly secure, real-time national intelligence dashboard for online voting. The platform features advanced data visualization, geo-spatial tracking of voting centers, and multi-layered security protocols to ensure absolute election integrity and real-time result monitoring across the territory.',
    image: 'https://picsum.photos/seed/voting-intel/1200/800',
    dataAiHint: 'digital dashboard map',
    techStack: ['Java / Spring Boot', 'PostgreSQL', 'D3.js', 'Cybersecurity Ops'],
    liveUrl: 'https://fbi-kenya-platform.vercel.app/',
    projectType: 'Systems',
    status: 'Sold',
  },
  {
    id: 'proj-1',
    title: 'Mpoa Wangu',
    description: 'A vibrant and user-friendly e-commerce platform for a premier flower and gift shop in Kenya.',
    longDescription: 'Designed and developed a stunning e-commerce experience for Mpoa Wangu. The platform allows customers to browse beautiful floral arrangements, select custom gifts, and place orders with ease. It features a mobile-first design, secure checkout, and a seamless interface tailored for the Kenyan flower market.',
    image: '/Screenshot 2026-02-14 053148.png',
    dataAiHint: 'flower shop ecommerce',
    techStack: ['Node.js', 'Next.js', 'Firebase', 'M-Pesa API'],
    liveUrl: 'https://mpoawangu.co.ke/',
    projectType: 'Web',
    status: 'Sold',
  },
  {
    id: 'proj-2',
    title: 'BEE AND DEE',
    description: 'A vibrant and engaging e-commerce website for a fashion and lifestyle brand.',
    longDescription: 'Created a visually appealing e-commerce platform for BEE AND DEE. The site features a dynamic product catalog, user-friendly navigation, and a streamlined shopping experience to drive sales and reflect the brand\'s unique identity. Built with a focus on mobile-first design and performance.',
    image: '/Screenshot 2026-01-01 090452.png',
    dataAiHint: 'fashion store screenshot',
    techStack: ['Dart / Flutter', 'Next.js', 'Tailwind CSS'],
    liveUrl: 'https://beeanddee.co.ke/',
    projectType: 'Web',
    status: 'Sold',
  },
  {
    id: 'proj-16',
    title: 'Business Hub ERP',
    description: 'Advanced business management system offered on a flexible lease subscription model.',
    longDescription: 'A comprehensive Enterprise Resource Planning (ERP) suite designed for African SMEs. It features inventory management, POS, and financial reporting, delivered through a scalable subscription lease model to ensure affordability and constant updates.',
    image: '/softwarefree.png',
    dataAiHint: 'erp dashboard',
    techStack: ['Go', 'Next.js', 'M-Pesa API', 'PostgreSQL'],
    liveUrl: 'https://businesshub.co.ke',
    projectType: 'Systems',
    status: 'Available',
    price: 3500,
  },
  {
    id: 'proj-7',
    title: 'Mobile Banking App Concept',
    description: 'A sleek and secure mobile app for a modern fintech company, designed for intuitive user experience.',
    longDescription: 'This project is a high-fidelity prototype of a mobile banking application. It features a clean, user-centric design, focusing on ease of use for everyday banking tasks like transfers, payments, and balance inquiries. The concept includes modern security features like biometric login and transaction notifications.',
    image: '/Screenshot 2026-01-01 092236.png',
    dataAiHint: 'mobile app finance',
    techStack: ['Dart / Flutter', 'Firebase', 'Biometric Auth'],
    liveUrl: 'https://dtbk.dtbafrica.com/',
    projectType: 'Mobile',
    status: 'Sold',
  },
  {
    id: 'proj-8',
    title: 'Point of Sale (POS) System',
    description: 'A reliable and fast Point of Sale system for retail stores, designed for quick checkouts and easy management.',
    longDescription: 'A robust POS system built for retail environments. It simplifies the checkout process, manages product inventory, and provides detailed sales reports. The system is designed to be user-friendly for cashiers and powerful for managers, supporting everything from barcode scanning to end-of-day reporting.',
    image: 'https://picsum.photos/seed/pos/600/400',
    dataAiHint: 'retail pos system',
    techStack: ['C# / .NET', 'SQL Server', 'WPF'],
    projectType: 'Systems',
    status: 'Available',
    price: 60000,
  }
];
