
import type { Project } from "@/components/projects/types";

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-17',
    title: 'National Intelligence Voting Platform',
    description: 'An advanced digital intelligence system designed for secure national-level online voting and geo-spatial data visualization.',
    longDescription: 'Engineered a highly secure, real-time national intelligence dashboard for online voting. The platform features advanced data visualization, geo-spatial tracking of voting centers, and multi-layered security protocols to ensure absolute election integrity and real-time result monitoring across the territory.',
    image: 'https://picsum.photos/seed/voting-intel/1200/800',
    dataAiHint: 'digital dashboard map',
    techStack: ['Next.js', 'PostgreSQL', 'D3.js', 'Firebase Auth', 'Cybersecurity'],
    liveUrl: 'https://fbi-kenya-platform.vercel.app/',
    projectType: 'Systems',
    status: 'Sold',
  },
  {
    id: 'proj-1',
    title: 'Mpoa Wangu',
    description: 'A vibrant and user-friendly e-commerce platform for a premier flower and gift shop in Kenya.',
    longDescription: 'Designed and developed a stunning e-commerce experience for Mpoa Wangu. The platform allows customers to browse beautiful floral arrangements, select custom gifts, and place orders with ease. It features a mobile-first design, secure checkout, and a seamless interface tailored for the Kenyan flower market.',
    image: '/Screenshot 2026-02-14 053148.png',
    dataAiHint: 'flower shop ecommerce',
    techStack: ['Next.js', 'React', 'Tailwind CSS', 'Firebase', 'M-Pesa API'],
    liveUrl: 'https://mpoawangu.co.ke/',
    projectType: 'Web',
    status: 'Sold',
  },
  {
    id: 'proj-2',
    title: 'BEE AND DEE',
    description: 'A vibrant and engaging e-commerce website for a fashion and lifestyle brand.',
    longDescription: 'Created a visually appealing e-commerce platform for BEE AND DEE. The site features a dynamic product catalog, user-friendly navigation, and a streamlined shopping experience to drive sales and reflect the brand\'s unique identity. Built with a focus on mobile-first design and performance.',
    image: '/Screenshot 2026-01-01 090452.png',
    dataAiHint: 'fashion store screenshot',
    techStack: ['Shopify', 'Liquid', 'JavaScript', 'Custom CSS'],
    liveUrl: 'https://beeanddee.co.ke/',
    projectType: 'Web',
    status: 'Sold',
  },
  {
    id: 'proj-3',
    title: 'Matesh Technologies',
    description: 'A modern and informative website for a tech company specializing in software and hardware solutions.',
    longDescription: 'Designed and implemented a sleek, modern website for Matesh Technologies. The platform clearly communicates their expertise in both software and hardware, featuring sections for services, products, and company information. The goal was to create a strong online presence that builds trust and generates leads.',
    image: '/Screenshot 2026-01-01 091103.png',
    dataAiHint: 'tech company',
    techStack: ['WordPress', 'PHP', 'Elementor', 'Custom Theme'],
    liveUrl: 'https://www.mateshtechnologies.co.ke/',
    projectType: 'Web',
    status: 'Sold',
  },
   {
    id: 'proj-4',
    title: 'SIMON STYLES Company Website',
    description: 'A personal portfolio site to showcase software development projects and skills.',
    longDescription: 'A clean, fast, and responsive personal portfolio website built to showcase a collection of software development projects. The site is designed to highlight technical skills and professional experience, featuring a project gallery, about me section, and contact form. Built with modern web technologies for optimal performance and user experience.',
    image: '/Screenshot 2026-01-01 092730.png',
    dataAiHint: 'developer portfolio',
    techStack: ['Next.js', 'Vercel', 'React', 'Tailwind CSS'],
    liveUrl: 'https://simon-websites.vercel.app/',
    projectType: 'Web',
    status: 'Sold',
  },
  {
    id: 'proj-5',
    title: 'House of Petals',
    description: 'A beautiful e-commerce website for a premier gift and flower shop, focusing on a great user shopping experience.',
    longDescription: 'Developed a charming and user-friendly e-commerce website for House of Petals. The site features an elegant design, easy product browsing, a secure checkout process, and is fully optimized for mobile devices to help customers find the perfect gift anytime, anywhere.',
    image: '/Screenshot 2026-01-01 091910.png',
    dataAiHint: 'flower shop',
    techStack: ['E-commerce', 'JavaScript', 'PHP', 'Online Payments'],
    liveUrl: 'https://houseofpetals.co.ke/',
    projectType: 'Web',
    status: 'Sold',
  },
  {
    id: 'proj-15',
    title: 'Henry Adeeya',
    description: 'A professional personal brand and consultancy platform for strategic leadership.',
    longDescription: 'Engineered a high-performance personal brand website for Henry Adeeya. The platform showcases professional achievements, thought leadership articles, and consultation booking capabilities with a focus on minimalist, high-end aesthetics.',
    image: 'https://picsum.photos/seed/henry/600/400',
    dataAiHint: 'professional consultant website',
    techStack: ['Next.js', 'Tailwind CSS', 'Framer Motion'],
    liveUrl: 'https://henryadeeya.com/',
    projectType: 'Web',
    status: 'Sold',
  },
  {
    id: 'proj-16',
    title: 'Business Hub ERP',
    description: 'Advanced business management system offered on a flexible lease subscription model.',
    longDescription: 'A comprehensive Enterprise Resource Planning (ERP) suite designed for African SMEs. It features inventory management, POS, and financial reporting, delivered through a scalable subscription lease model to ensure affordability and constant updates.',
    image: '/softwarefree.png',
    dataAiHint: 'erp dashboard',
    techStack: ['Next.js', 'Firebase', 'M-Pesa API', 'PostgreSQL'],
    liveUrl: 'https://businesshub.co.ke',
    projectType: 'Systems',
    status: 'Available',
    price: 3500, // Monthly lease price example
  },
  {
    id: 'proj-14',
    title: 'Ilorie Consult Limited',
    description: 'A professional website for a consultancy firm specializing in company registrations and KRA services.',
    longDescription: 'Developed a professional website for Ilorie Consult Limited, a firm specializing in company registrations, KRA consultations, and other BRS services. The site is designed to provide clear information to clients and establish a strong professional online presence.',
    image: '/Screenshot 2026-01-01 091301.png',
    dataAiHint: 'consulting website',
    techStack: ['React', 'Next.js', 'Tailwind CSS', 'Vercel'],
    liveUrl: 'https://ilorieconsult.com/',
    projectType: 'Web',
    status: 'Sold',
  },
  {
    id: 'proj-6',
    title: 'Inventory Management System',
    description: 'A comprehensive system for tracking stock levels, orders, sales, and deliveries for a small business.',
    longDescription: 'This custom-built Inventory Management System helps small businesses take control of their stock. It provides real-time tracking of inventory levels, manages purchase orders, tracks sales, and streamlines the delivery process. The intuitive dashboard offers valuable insights into stock turnover and sales performance.',
    image: 'https://picsum.photos/seed/inventory/600/400',
    dataAiHint: 'dashboard management system',
    techStack: ['React', 'Node.js', 'Express', 'MongoDB'],
    projectType: 'Systems',
    status: 'Available',
    price: 60000,
  },
  {
    id: 'proj-7',
    title: 'Mobile Banking App Concept',
    description: 'A sleek and secure mobile app for a modern fintech company, designed for intuitive user experience.',
    longDescription: 'This project is a high-fidelity prototype of a mobile banking application. It features a clean, user-centric design, focusing on ease of use for everyday banking tasks like transfers, payments, and balance inquiries. The concept includes modern security features like biometric login and transaction notifications.',
    image: '/Screenshot 2026-01-01 092236.png',
    dataAiHint: 'mobile app finance',
    techStack: ['Flutter', 'Dart', 'Firebase', 'Figma'],
    liveUrl: 'https://dtbk.dtbafrica.com/',
    projectType: 'Mobile',
    status: 'Sold',
  },
  {
    id: 'proj-8',
    title: 'Point of Sale (POS) System',
    description: 'A reliable and fast Point of Sale system for retail stores, designed for quick checkouts and easy management.',
    longDescription: 'A robust POS system built for retail environments. It simplifies the checkout process, manages product inventory, and provides detailed sales reports. The system is designed to be user-friendly for cashiers and powerful for managers, supporting everything from barcode scanning to end-of-day reporting.',
    image: 'https://picsum.photos/seed/pos/600/400',
    dataAiHint: 'retail pos system',
    techStack: ['C#', '.NET', 'SQL Server', 'WPF'],
    projectType: 'Systems',
    status: 'Available',
    price: 60000,
  },
  {
    id: 'proj-9',
    title: 'Real Estate Listings Platform',
    description: 'A web platform for a real estate agency to list properties and connect with potential buyers.',
    longDescription: 'This platform allows real estate agents to easily upload and manage property listings. Potential buyers can search and filter properties based on various criteria, view high-quality images, and contact agents directly. The design focuses on showcasing properties in the best light and generating leads for the agency.',
    image: 'https://picsum.photos/seed/realestate/600/400',
    dataAiHint: 'real estate website',
    techStack: ['Vue.js', 'Nuxt.js', 'Firebase', 'Tailwind CSS'],
    projectType: 'Web',
    status: 'Sold',
  },
  {
    id: 'proj-10',
    title: 'Restaurant Booking System',
    description: 'An online reservation system for a fine-dining restaurant, allowing customers to book tables in advance.',
    longDescription: 'A custom booking system that lets diners reserve tables easily. The restaurant staff can manage reservations through a simple admin panel, view upcoming bookings, and manage table availability. This system helps reduce no-shows and streamlines the reservation process.',
    image: 'https://picsum.photos/seed/restaurant/600/400',
    dataAiHint: 'restaurant booking',
    techStack: ['Laravel', 'PHP', 'MySQL', 'JavaScript'],
    projectType: 'Systems',
    status: 'Sold',
  },
  {
    id: 'proj-11',
    title: 'Event Ticketing Mobile App',
    description: 'A mobile app for users to discover, buy, and manage tickets for local events.',
    longDescription: 'This app provides a seamless experience for event-goers. Users can browse upcoming events, purchase tickets securely, and access their tickets with a QR code. Event organizers can manage their listings and track sales through a dedicated dashboard.',
    image: 'https://picsum.photos/seed/ticketing/600/400',
    dataAiHint: 'event tickets app',
    techStack: ['React Native', 'Firebase', 'Stripe API'],
    projectType: 'Mobile',
    status: 'Available',
    price: 140000,
  },
  {
    id: 'proj-12',
    title: 'School Management System',
    description: 'An all-in-one system for schools to manage student information, grades, attendance, and communication.',
    longDescription: 'A comprehensive school management portal that streamlines administrative tasks. It provides modules for student records, grade books, attendance tracking, and parent-teacher communication. The system is designed to be secure, reliable, and easy to use for administrators, teachers, and parents.',
    image: 'https://picsum.photos/seed/schoolsystem/600/400',
    dataAiHint: 'school dashboard',
    techStack: ['Django', 'Python', 'PostgreSQL', 'React'],
    projectType: 'Systems',
    status: 'Sold',
  },
  {
    id: 'proj-13',
    title: 'Online Learning Platform',
    description: 'An e-learning website with video courses, quizzes, and progress tracking for students.',
    longDescription: 'This platform allows instructors to create and sell online courses. Students can enroll, watch video lessons, take quizzes to test their knowledge, and track their progress. It\'s a complete solution for creating an online educational community.',
    image: 'https://picsum.photos/seed/elearning/600/400',
    dataAiHint: 'online course',
    techStack: ['Ruby on Rails', 'Heroku', 'PostgreSQL', 'JavaScript'],
    projectType: 'Web',
    status: 'Available',
    price: 30000,
  }
];
